### PR TITLE
Feature/14

### LINKED ISSUE #14: Completely port all Casper tests to Puppetter and Jest
Following the prototype [here](https://github.com/openworm/geppetto-application/issues/13) finish porting all Casper tests of Geppetto application

### PR DESCRIPTION
**Pull request by afonsobspinto**
Closes #14

### CODE REVIEW

**Comment by tarelli** [comment]
@tarelli this can be merged

**Review by tarelli — CHANGES_REQUESTED** [review]
@afonsobspinto @jrmartin let's add back the package.lock

**Comment by jrmartin** [comment]
@tarelli @afonsobspinto package.lock.json added back, tests passed. 

https://travis-ci.org/openworm/geppetto-application/builds/595240252

**Review by jrmartin — APPROVED** [review]
All good

**Comment by tarelli** [comment]
@jrmartin why do you have node_modules inside geppetto-client at all? check with @afonsobspinto he was also having that problem, but node_modules should only be inside webapp(geppetto-application)

**Comment by jrmartin** [comment]
@tarelli Locally, I have node_modules under webapp. Only in travis I'm seeing the node_modules get created inside geppetto_client, at least griddle is there since that's the one with eslint errors.

**Comment by jrmartin** [comment]
@tarelli I removed the geppetto_client/node_modules/griddle exclusion from .gitignore, turns out the package-lock.json was causing trouble in travis, but an update fix it.

**Comment by jrmartin** [comment]
@tarelli Conflicts are gone

**Pull request merged**
