### PR TITLE
Feature/geppetto client#35

### PR DESCRIPTION
**Pull request by jrmartin**
Changes needed after dependency changes in openworm/geppetto-client#35 .  

- Webpack dependency upgrading from version 3 to 4, webpack needs now the flag '--mode' to run. Right now is has been set to '--mode none', [the options](https://webpack.js.org/configuration/mode/).

- Uses mini-css-extract-plugin instead of extract-text-webpack-plugin as css-loader.

-  webpack.optimize.CommonsChunkPlugin becomes [splitchunks](https://github.com/openworm/geppetto-application/compare/development...feature/geppetto-client%2335?expand=1#diff-11e9f7f953edc64ba14b0cc350ae7b9dR65) in webpack 4.

Build folder file output using CommonsChunkPlugin in webpack 3 vs using SplitChunksPlugin in webpack 4.
(Webpack 3 CommonsChunkPlugin on Left vs Webpack 4 SplitChunksPlugin on Right)
Screenshot from 2019-07-11 13-36-04
Main visible difference is that main.bundle.js got reduced and is now 11.2 kb instead of 6.65 MB and that common.bundle.js size increase and is now 7.26 mb instead of 1.69 mb.

After changing some settings  in commit https://github.com/openworm/geppetto-application/pull/15/commits/38875627b4a3598d5d12405f7afbf53c0e77262c, the main.js and common.bundle.js are now similar size to what they were in webpack 3.   

Passing travis test https://travis-ci.org/openworm/geppetto-application/builds/562163182

### CODE REVIEW

**Comment by tarelli** [comment]
@jrmartin I merged another PR first and this now has conflicts, can you resolve them?

**Comment by jrmartin** [comment]
@tarelli Conflicts have been resolved,  passing  https://travis-ci.org/openworm/geppetto-application/builds/562163182

**Comment by filippomc** [comment]
I tried it on windows with the last version of npm and the install worked.
Couldn't go further due to a problem with the build in windows (see #19)

**Comment by tarelli** [comment]
@filippomc #18 seems unrelated?

**Comment by filippomc** [comment]
@tarelli yes it's a problem also with the development branch.

**Comment by tarelli** [comment]
I think this is the issue you are referring to https://github.com/openworm/geppetto-application/issues/19

**Comment by afonsobspinto** [comment]
Fixes #12  as well :+1:

**Review by tarelli — APPROVED** [review]

**Pull request merged**
