### PR TITLE
#47 fix package-lock for the underscore version

### PR DESCRIPTION
**Pull request by ddelpiano**
- updating package-lock due to the problem with the underscore library

### CODE REVIEW

**Comment by tarelli** [comment]
@ddelpiano needs to be updated with latest from dev?

**Review by filippomc — COMMENTED** [review]
@ddelpiano how was this otained? Only a new fresh npm install?

**Comment by ddelpiano** [comment]
@filippomc yes

**Review by filippomc — CHANGES_REQUESTED** [review]
I see a conflict, possible that the new version from dev already has the update?

**Pull request closed without merging**
