### PR TITLE
Fix/49

### LINKED ISSUE #49: fix jest tests

### PR DESCRIPTION
**Pull request by ddelpiano**
- Fix jest puppeter tests ignoring whatever unit tests has been implemented within geppetto-client (not supposed to run along the geppetto-application tests).
- changed the baseURL parameter retrieval

### CODE REVIEW

**Comment by tarelli** [comment]
that's great @ddelpiano! @filippomc tests are now passing again, can you also review make sure we are on the same page with the latest?

**Review by tarelli — APPROVED** [review]

**Review by filippomc — APPROVED** [review]
Nothing controversial here. Let me just point out that the name of the branch is not in line with gitflow recommendations. That the name of the branch, `fix` or `feature` is not related to the nature of the task, but rather by the merge workflow. fix/* should be used for hotfixes, which start from master and end on both master and development.

**Comment by ddelpiano** [comment]
> Nothing controversial here. Let me just point out that the name of the branch is not in line with gitflow recommendations. That the name of the branch, `fix` or `feature` is not related to the nature of the task, but rather by the merge workflow. fix/* should be used for hotfixes, which start from master and end on both master and development.

@filippomc in the gitflow recommendation is stated to use branch names as hotfix_X.X.X where the X.X.X points to the version we aim to release as hotifx, I did not see any recommendation related to the use of fix/issue_number. If fix/## should be reserved for that we should integrate this in the documentation.

**Comment by filippomc** [comment]
> > Nothing controversial here. Let me just point out that the name of the branch is not in line with gitflow recommendations. That the name of the branch, `fix` or `feature` is not related to the nature of the task, but rather by the merge workflow. fix/* should be used for hotfixes, which start from master and end on both master and development.
> 
> @filippomc in the gitflow recommendation is stated to use branch names as hotfix_X.X.X where the X.X.X points to the version we aim to release as hotifx, I did not see any recommendation related to the use of fix/issue_number. If fix/## should be reserved for that we should integrate this in the documentation.

@ddelpiano yes you're right the default name is `hotfix`, but the name templates are configurable and `fix` looks like that :) There are no other categories other than  features, hotfixes, releases, and I see no reason to not stick to these 3 categories!

**Pull request merged**
